blog/urls.py
from blog.views import *
from django.urls import path
app_name="blog"
urlpatterns=[
    path('',blog_home,name='home'),
    path('<int:pid>',blog_single,name="single"),
    path('category/<str:cat_name>',blog_home,name='category'),
    path('tag/<str:tag_name>',blog_home,name='tag'),
    path('author/<str:author_username>/',blog_home, name='author'),
    path( 'search/', blog_search , name= "search"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.conf import settings
import debug_toolbar
sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    #summernote
    path('summernote/', include('django_summernote.urls')),
    #robots
    path('robots.txt', include('robots.urls')),
    #captcha
    path('captcha/', include('captcha.urls')),
    #debug
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.error_views.error_404"  

website/urls.py
from website.views import *
from django.urls import path
app_name="web"
urlpatterns=[
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter,name="newsletter")
]

templates/web/about.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <main id="main">
        <!-- ======= About Section ======= -->
        <section id="about" class="about">
    
          <div class="container" data-aos="fade-up">
            <div class="row gx-0">
    
              <div class="col-lg-6 d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="200">
                <div class="content">
                  <h3>Who We Are</h3>
                  <h2>Expedita voluptas omnis cupiditate totam eveniet nobis sint iste. Dolores est repellat corrupti
                    reprehenderit.</h2>
                  <p>
                    Quisquam vel ut sint cum eos hic dolores aperiam. Sed deserunt et. Inventore et et dolor consequatur
                    itaque ut voluptate sed et. Magnam nam ipsum tenetur suscipit voluptatum nam et est corrupti.
                  </p>
                  
                </div>
              </div>
    
              <div class="col-lg-6 d-flex align-items-center" data-aos="zoom-out" data-aos-delay="200">
                <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="">
              </div>
    
            </div>
          </div>
    
        </section><!-- End About Section -->
    </main>
      <!-- ======= Footer ======= -->
  {% endblock %}

templates/web/contact.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
<!-- Include Bootstrap CSS -->

<style>
    .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
    }
    .form-group {
        margin-bottom: 20px;
    }
    .form-group.inline {
        display: flex;
    }
    /* اعمال استایل‌ها برای ورودی‌های نام و ایمیل */
    .form-group.inline input[type="text"],
    .form-group.inline input[type="email"] {
        flex: 1;
        margin-right: 10px;
    }

    

    .form-group textarea {
        width: 100%;
    }
    .form-group.captcha {
        text-align: center;
    }
    .form-group.captcha img {
        display: inline-block;
        margin-bottom: 10px;
    }
    .form-group.button {
        text-align: center;
    }
</style>
{% endblock %}

{% block body %}
<main id="main">
    <section id="contact" class="contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="contact-container" data-aos="fade-up">
                        <header class="section-header text-center">
                            <h2>Contact</h2>
                            <p>Contact Us</p>
                        </header>
                        <form action="{% url 'web:contact' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group inline">
                                <input name="name" placeholder="Enter your name" class="form-control" required type="text"><br>
                                <input name="email" placeholder="Enter email address" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" class="form-control" required type="email"><br>
                            </div>
                            
                            <div class="form-group">
                                <input name="subject" placeholder="Enter subject" class="form-control" required type="text"><br>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="message" placeholder="Enter Message" rows="6" required></textarea><br>
                            </div>
                            {{ form.captcha }}
                            <button class="btn btn-primary" type="submit">Send Message</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock %}

{% block scripts %}
<!-- Include Bootstrap JS -->

{% endblock %}

templates/web/index.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block body %}
  <!-- ======= Hero Section ======= -->
  <section id="hero" class="hero d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 d-flex flex-column justify-content-center">
          <h1 data-aos="fade-up">We offer modern solutions for growing your business</h1>
          <h2 data-aos="fade-up" data-aos-delay="400">We are team of talented designers making websites with Bootstrap
          </h2>
          <div data-aos="fade-up" data-aos-delay="600">
            <div class="text-center text-lg-start">
            </div>
          </div>
        </div>
        <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
          <img src="{% static 'assets/img/hero-img.png' %}" class="img-fluid" alt="">
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">
    <!-- ======= Counts Section ======= -->
    <section id="counts" class="counts">
      <div class="container" data-aos="fade-up">

        <div class="row gy-4">

          <div class="col-lg-3 col-md-6">
            <div class="count-box">
              <i class="bi bi-emoji-smile"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>Happy Clients</p>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="count-box">
              <i class="bi bi-journal-richtext" style="color: #ee6c20;"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>Projects</p>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="count-box">
              <i class="bi bi-headset" style="color: #15be56;"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="1463" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>Hours Of Support</p>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="count-box">
              <i class="bi bi-people" style="color: #bb0852;"></i>
              <div>
                <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1"
                  class="purecounter"></span>
                <p>Hard Workers</p>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- End Counts Section -->

    <!-- ======= Features Section ======= -->
    <section id="features" class="features">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h2>Features</h2>
          <p>Laboriosam et omnis fuga quis dolor direda fara</p>
        </header>

        <div class="row">

          <div class="col-lg-6">
            <img src="{% static 'assets/img/features.png' %}" class="img-fluid" alt="">
          </div>

          <div class="col-lg-6 mt-5 mt-lg-0 d-flex">
            <div class="row align-self-center gy-4">

              <div class="col-md-6" data-aos="zoom-out" data-aos-delay="200">
                <div class="feature-box d-flex align-items-center">
                  <i class="bi bi-check"></i>
                  <h3>Eos aspernatur rem</h3>
                </div>
              </div>

              <div class="col-md-6" data-aos="zoom-out" data-aos-delay="300">
                <div class="feature-box d-flex align-items-center">
                  <i class="bi bi-check"></i>
                  <h3>Facilis neque ipsa</h3>
                </div>
              </div>

              <div class="col-md-6" data-aos="zoom-out" data-aos-delay="400">
                <div class="feature-box d-flex align-items-center">
                  <i class="bi bi-check"></i>
                  <h3>Volup amet voluptas</h3>
                </div>
              </div>

              <div class="col-md-6" data-aos="zoom-out" data-aos-delay="500">
                <div class="feature-box d-flex align-items-center">
                  <i class="bi bi-check"></i>
                  <h3>Rerum omnis sint</h3>
                </div>
              </div>

              <div class="col-md-6" data-aos="zoom-out" data-aos-delay="600">
                <div class="feature-box d-flex align-items-center">
                  <i class="bi bi-check"></i>
                  <h3>Alias possimus</h3>
                </div>
              </div>

              <div class="col-md-6" data-aos="zoom-out" data-aos-delay="700">
                <div class="feature-box d-flex align-items-center">
                  <i class="bi bi-check"></i>
                  <h3>Repellendus mollitia</h3>
                </div>
              </div>

            </div>
          </div>

        </div> <!-- / row -->

    </section><!-- End Features Section -->

    <!-- ======= Recent Blog Posts Section ======= -->
    {% recent  %}
    <!-- End Recent Blog Posts Section -->

  </main><!-- End #main -->
{% endblock %}

templates/web/recent-blog.html
{% load static %}
{% load humanize %}
{% load blog_tags %}
<section id="recent-blog-posts" class="recent-blog-posts">
    <div class="container" data-aos="fade-up">
        <header class="section-header">
            <h2>Blog</h2>
            <p>Recent posts form our Blog</p>
        </header>
        <div class="row">
            {% for post in posts %}
            <div class="col-lg-4">
                <div class="post-box">
                    <div class="post-img"><img src="{{post.image.url}}" class="img-fluid" alt="{% url 'blog:single' pid=post.id %}"></div>
                    <span class="post-date">{{post.published_date|date:"d/m/Y"}}</span>
                    <h3 class="post-title">{{ post.title }}</h3>
                    <a href="{% url 'blog:single' pid=post.id %}" class="readmore stretched-link mt-auto"><span>Read
                            More</span><i class="bi bi-arrow-right"></i></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>