blog/urls.py
from blog.views import *
from django.urls import path
app_name="blog"
urlpatterns=[
    path('',blog_home,name='home'),
    path('<int:pid>',blog_single,name="single"),
    path('category/<str:cat_name>',blog_home,name='category'),
    path('tag/<str:tag_name>',blog_home,name='tag'),
    path('author/<str:author_username>/',blog_home, name='author'),
    path( 'search/', blog_search , name= "search"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.conf import settings
import debug_toolbar
sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    #summernote
    path('summernote/', include('django_summernote.urls')),
    #robots
    path('robots.txt', include('robots.urls')),
    #captcha
    path('captcha/', include('captcha.urls')),
    #debug
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.error_views.error_404"  

website/urls.py
from website.views import *
from django.urls import path
app_name="web"
urlpatterns=[
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter,name="newsletter")
]

blog/models.py
#makemigrations و migrate

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/' , default='blog-1.jpg')
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.SET_NULL , null=True)
    content = models.TextField()
    tag = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_required = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    uptodate = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} {}'.format(self.title,self.id)
    
    class Meta:
        ordering=['-created_date']
    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})
    

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    subject = models.CharField(max_length=255)
    message=models.TextField()
    approwed=models.BooleanField(default=False)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['-created_date']
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Comment

class Commentforms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'subject', 'message', 'post']

blog/views.py
from django.shortcuts import render ,get_object_or_404 , redirect
from blog.models import Comment , Post 
from blog.forms import Commentforms
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect ,Http404

# Create your views here.
def blog_home(request , **kwargs):
    currnt_time = timezone.now()
    posts = Post.objects.filter(published_date__lte = currnt_time , status = 1)
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name = kwargs['cat_name'])
    if kwargs.get('tag_name') != None:
        posts=posts.filter(tag__name__in=[kwargs['tag_name']])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username =kwargs['author_username'])
    posts = Paginator( posts, 3)
    try :
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage :
        posts = posts.get_page(1)
    context = {'posts':posts }
    return render(request, 'blog/blog-home.html' , context)




def blog_single(request , pid):
    if request.method == 'POST':
        form = Commentforms(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'Your comment has been registered. Then the review will be displayed')
        else:
            messages.add_message(request,messages.ERROR,'your tikct didnt submited')
    currnt_time=timezone.now()
    posts=get_object_or_404(Post,pk=pid,status=1,published_date__lte=currnt_time)
    next_post = Post.objects.filter(id__gt=pid, status=1, published_date__lte=currnt_time).order_by('id').first()
    prev_post = Post.objects.filter(id__lt=pid, status=1, published_date__lte=currnt_time).order_by('-id').first()
    posts.counted_views+=1
    posts.save()
    if posts.login_required==False:
        comments=Comment.objects.filter(post=posts.id,approwed=True)
        form=Commentforms()
        context={'post':posts,'comments':comments,'next_post':next_post,'prev_post':prev_post,'form':form}
        return render(request,'blog/blog-single.html',context)  
    elif posts.login_required==True and request.user.is_authenticated:
        posts.login_required=False
        comments=Comment.objects.filter(post=posts.id,approwed=True)
        form=Commentforms()
        context={'post':posts,'comments':comments,'next_post':next_post,'prev_post':prev_post,'form':form}
        return render(request,'blog/blog-single.html',context)
    return HttpResponseRedirect(reverse('login'))



def blog_category(request,cat_name):
    currnt_time=timezone.now()
    posts=Post.objects.filter(status=1,published_date__lte=currnt_time)
    posts=posts.filter(category__name=cat_name)
    if not posts.exists():
        messages.add_message(request,messages.ERROR,'The desired phrase was not found. Please try again')
        return HttpResponseRedirect('/blog/')  
    context={'posts':posts}
    return render(request,'blog/blog-caregories.html',context)


def blog_search(request):
    current_time = timezone.now()
    posts = Post.objects.filter(status=1, published_date__lte=current_time)
    if 's' in request.GET:
        s = request.GET.get('s')
        if s:
            posts = posts.filter(content__contains=s)
    if not posts.exists():
        messages.add_message(request,messages.ERROR,'The desired phrase was not found. Please try again')
        return HttpResponseRedirect('/blog/')    
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/blog-author.html
{% load static %}
<div class="blog-author d-flex align-items-center">
    <img src="{% static 'assets/img/blog/blog-author.jpg' %}" class="rounded-circle float-left" alt="">
    <div>
      <h4>{{post.author.get_full_name}}</h4>
      <div class="social-links">
        <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
        <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
        <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
      </div>
      <p>
        Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
      </p>
    </div>
  </div><!-- End blog author bio -->

templates/blog/blog-caregories.html
{% load static %}
{% load blog_tags %}
<h3 class="sidebar-title">Categories</h3>
<div class="sidebar-item categories">
  <ul>
    {% for name,count in categories.items %}
        <li><a href="{% url 'blog:category' cat_name=name %}">{{name}}<span>({{count}})</span></a></li>
        {% endfor %} 
  </ul>
</div><!-- End sidebar categories-->

templates/blog/blog-comments.html
{% load static %}
{% load humanize %}
<div class="blog-comments">

    <h4 class="comments-count">{{comments|length}} Comments</h4>

    <div id="comments" class="comment-section">
      {% for comment in comments %}
      <div id="comment-{{ forloop.counter }}" class="comment">
        <div class="d-flex">
          <div class="comment-img"><img src="{% static 'assets/img/blog/comments-1.jpg' %}" alt=""></div>
          <div>
            <h5>{{ comment.name }}</h5>
            <time>{{ comment.created_date|naturalday }}</time>
            <p>{{ comment.message|safe }}</p>
          </div>
        </div>
      </div><!-- End comment #{{ forloop.counter }} -->
      {% endfor %}
    </div><!-- End comments -->
    

    <div class="reply-form">
      <h4>Comment</h4>
      <p>Your email address will not be published. Required fields are marked * </p>
      <form action="{% url 'blog:single' pid=post.id  %}" method="post">
        <div class="row">
          {% csrf_token %}
          <input type="hidden" name="post" value="{{post.id}}">
          {% if request.user.is_authenticated %}
          <div class="col-md-6 form-group">
            <input name="name" type="hidden" class="form-control" placeholder="Your Name*" value="{{request.user.first_name}}">
          </div>
          <div class="col-md-6 form-group">
            <input name="email" type="hidden" class="form-control" placeholder="Your Email*" value="{{request.user.email}}">
          </div>
          {% else %}
          <div class="col-md-6 form-group">
            <input name="name" type="text" class="form-control" placeholder="Your Name*">
          </div>
          <div class="col-md-6 form-group">
            <input name="email" type="text" class="form-control" placeholder="Your Email*">
          </div>
          {% endif %}
        </div>
        <div class="row">
          <div class="col form-group">
            <input name="subject" type="text" class="form-control" placeholder="Your subject">
          </div>
        </div>
        <div class="row">
          <div class="col form-group">
            <textarea name="message" class="form-control" placeholder="Your Comment*"></textarea>
          </div>
        </div>

        <button type="submit" class="btn btn-primary">Post Comment</button>

      </form>

    </div>

  </div><!-- End blog comments -->

templates/blog/blog-home.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block body %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">
      <ol>
        <li><a href="{% url 'web:index' %}">Home</a></li>
        <li>Blog</li>
      </ol>
      <h2>Blog</h2>
    </div>
  </section><!-- End Breadcrumbs -->
  <!-- ======= Blog Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">
     
      <div class="row">
        <div class="col-lg-8 entries">
          {% for post in posts %}
          <article class="entry">
            <div class="entry-img">
              <img src="{{post.image.url}}" alt="" class="img-fluid">
            </div>
            <h2 class="entry-title">
              <a href="{% url 'blog:single'  pid=post.id%}">{{post.title}}</a>
            </h2>
            {% for cat in post.category.all %}
                <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}{% if not forloop.last %},{% endif %}</a>
              {% endfor %}
            <div class="entry-meta">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i><time datetime="2020-01-01">{{post.published_date|date:"d/m/Y"}}</time></li>  
                <li class="d-flex align-items-center"><i class="bi bi-eye"></i>{{post.counted_views}} views</li>
              </ul>
            </div>
            <div class="entry-content">
              <p>
                {{post.content|safe|truncatewords:10}}
              </p>
              <div class="read-more">
                <a href="{% url 'blog:single'  pid=post.id%}">Read More</a>
              </div>
            </div>
          </article><!-- End blog entry -->
          {% endfor %}
          <nav class="blog-pagination justify-content-center d-flex">
            <ul class="pagination">
                <li class="page-item">
                    {% if posts.has_previous %}
                        <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                            <span aria-hidden="true">
                                <span class="lnr lnr-chevron-left"></span>
                            </span>
                        </a>
                    {% endif %}
                </li>
                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% else %}
                        <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% endif %}
                {% endfor %}
                <li class="page-item">
                    {% if posts.has_next %}
                        <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                            <span aria-hidden="true">
                                <span class="lnr lnr-chevron-right"></span>
                            </span>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>
        </div><!-- End blog entries list -->
        <div class="col-lg-4">
          <div class="sidebar">
            {% include 'blog/blog-search.html' %}
            {% postcategotys %}
            {% lastposts %}
          </div><!-- End sidebar -->
        </div><!-- End blog sidebar -->
      </div>
    </div>
  </section><!-- End Blog Section -->
</main><!-- End #main -->
<!-- ======= Footer ======= -->
{% endblock %}

templates/blog/blog-recent-post.html
{% load static %}
{% load humanize %} 
{% load blog_tags %}
<h3 class="sidebar-title">Recent Posts</h3>
            <div class="sidebar-item recent-posts">
              {% for post in posts %}
              <div class="post-item clearfix">
                <img src="{{post.image.url}}" alt="">
                <h4><a href="{% url 'blog:single'  pid=post.id %}">{{post.title}}</a></h4>
                <p>    {{post.published_date|naturaltime}}</p>
                {% endfor %}
              </div>


            </div><!-- End sidebar recent posts-->

templates/blog/blog-search.html
<h3 class="sidebar-title">Search</h3>
            <div class="sidebar-item search-form">
              <form action="{% url 'blog:search' %}" method="get">
                <input type="text" name="s">
                <button type="submit"><i class="bi bi-search"></i></button>
              </form>
            </div><!-- End sidebar search formn-->

templates/blog/blog-single.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block body %}

<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <section class="breadcrumbs">
    <div class="container">
      <ol>
        <li><a href="{% url 'web:index' %}">Home</a></li>
        <li><a href="{% url 'blog:home' %}">Blog</a></li>
        <li>Blog Single</li>
      </ol>
      <h2>Blog Single</h2>
    </div>
  </section><!-- End Breadcrumbs -->
  <!-- ======= Blog Single Section ======= -->
  <section id="blog" class="blog">
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-8 entries">
          <article class="entry entry-single">
            <div class="entry-img">
              <img src="{{post.image.url}}" alt="" class="img-fluid">
            </div>
            <h2 class="entry-title">
              {{post.title}}
            </h2>
            <div class="entry-meta">
              <ul>
                <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                    href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a>
                </li>
                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> {{post.published_date|date:"d/m/Y"}}
                </li>
                <li class="d-flex align-items-center"><i class="bi bi-eye"></i>{{post.counted_views}} views</li>
                <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i>{{post.comments|length}}
                  Comments</li>
              </ul>
            </div>
            <div class="entry-content">
              <p>
                {{post.content|safe}}
            </div>
            <div class="">
              <div class="nex-prev-post" style="display: flex; justify-content: space-between;">
                <div calss="next" dir="ltr">
                {% if next_post %}
                <div class="next-post" >
                    <a href="{% url 'blog:single' next_post.id %}">
                        <img src="{{next_post.image.url}}" width="95" height="60">
                        <p style="font-size: 25px;"><a href="{% url 'blog:single' next_post.id %}">{{next_post.title}}</a></p>
                    </a>
                </div>
              
                {% endif %}
              </div>
                <div class="prev" dir="rtl">
                {% if prev_post %}
                <div class="next-post" >
                    <a href="{% url 'blog:single' prev_post.id %}">
                        <img src="{{prev_post.image.url}}" width="95" height="60">
                        <p style="font-size: 25px;"><a href="{% url 'blog:single' prev_post.id %}">{{prev_post.title}}</a></p>
                    </a>
                </div>
                {% endif %}
              </div>
            </div>
            
      </div>
            <div class="entry-footer">
              <i class="bi bi-folder"></i>
              
              <ul class="cats">
                {% for cat in post.category.all %}
                <li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}{% if not forloop.last %},{% endif%}
                    </a></li>
                {% endfor %}
              </ul>
              <i class="bi bi-tags"></i>
              <ul class="tags">
                {% for tags in post.tag.all %}
                <li><a href="{% url 'blog:tag' tag_name=tags.name %}">{{tags.name}}{% if not forloop.last %}{% endif%}
                    </a></li>
                {% endfor %}
              </ul>
            </div>
          </article><!-- End blog entry -->
          {% include 'blog/blog-author.html' %}
          {% include 'blog/blog-comments.html' %}
        </div><!-- End blog entries list -->
        <div class="col-lg-4">
          <div class="sidebar">
            {% postcategotys %}
            {% lastposts %}
            {% include 'blog/blog-tag.html' %}
          </div><!-- End sidebar -->
        </div><!-- End blog sidebar -->
      </div>
    </div>
  </section><!-- End Blog Single Section -->
</main><!-- End #main -->
<!-- ======= Footer ======= -->
{% endblock %}

templates/blog/blog-tag.html
<h3 class="sidebar-title">Tags</h3>
            <div class="sidebar-item tags">
              <ul>
                {% for tag in post.tag.all %}
                <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a></li>
                {% endfor %}
              </ul>
            </div><!-- End sidebar tags-->