blog/urls.py
from blog.views import *
from django.urls import path
app_name="blog"
urlpatterns=[
    path('',blog_home,name='home'),
    path('<int:pid>',blog_single,name="single"),
    path('category/<str:cat_name>',blog_home,name='category'),
    path('tag/<str:tag_name>',blog_home,name='tag'),
    path('author/<str:author_username>/',blog_home, name='author'),
    path( 'search/', blog_search , name= "search"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from django.conf import settings
import debug_toolbar
sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    #summernote
    path('summernote/', include('django_summernote.urls')),
    #robots
    path('robots.txt', include('robots.urls')),
    #captcha
    path('captcha/', include('captcha.urls')),
    #debug
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.error_views.error_404"  

website/urls.py
from website.views import *
from django.urls import path
app_name="web"
urlpatterns=[
    path('',index_view,name='index'),
    path('about',about_view,name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter,name="newsletter")
]

templates/base.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>ProjectAskari</title>
    <meta name="description" content="Description of your website including primary keywords">
    <meta content="" name="keywords">
    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    {% compress css %}
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    {% endcompress %}
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
            <a href="{% url 'web:index' %}" class="logo d-flex align-items-center">
                <img src="{% static 'assets/img/logo.png' %}" alt="">
                <span>ProjectAskari</span>
            </a>
            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="{% url 'web:index' %}">Home</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'web:about' %}">About</a></li>
                    <li><a href="{% url 'blog:home' %}">Blog</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'web:contact' %}">Contact</a></li>
                    {% if request.user.is_authenticated %}
                    <li><a class="getstarted scrollto">{{request.user.username}}</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="getstarted scrollto" href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
        </div>
    </header><!-- End Header -->
    {% block body %}


    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        {% if messages %}
        {% for message in messages %}
        Swal.fire({
            title: "{{ message.tags }}",
            text: "{{ message }}",
            icon: "{{ message.tags }}",
            timer: 5000
        });
        {% endfor %}
        {% endif %}
    </script>
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-newsletter">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12 text-center">
                        <h4>Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    </div>
                    <div class="col-lg-6">
                        <form action="{% url 'web:newsletter' %}" method="post">
                            {% csrf_token %}   
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-top">
            <div class="container">
                <div class="row gy-4">
                    <div class="col-lg-5 col-md-12 footer-info">
                        <a href="{% url 'web:index' %}" class="logo d-flex align-items-center">
                            <img src="{% static 'assets/img/logo.png' %}" alt="">
                            <span>ProjectAskari</span>
                        </a>
                        <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita
                            valies
                            darta donna mare fermentum iaculis eu non diam phasellus.</p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <a href="{% url 'web:index' %}">Home</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="{% url 'web:about' %}">About us</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="{% url 'blog:home' %}">Blog</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="{% url 'web:contact' %}">Contact</a></li>
                        </ul>
                    </div>

                   

                    <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                        <h4>Contact Us</h4>
                        <p>
                            A108 Adam Street <br>
                            New York, NY 535022<br>
                            United States <br><br>
                            <strong>Phone:</strong> +98 992 077 3043<br>
                            <strong>Email:</strong> elyaaskarii86@gmail.com<br>
                        </p>

                    </div>

                </div>
            </div>
        </div>

       
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    {% compress js %}
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% endcompress %}

</body>

</html>